######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 14 23:22:00 2013
######################################################################

TEMPLATE = app
TARGET = QtCounterGUI
#DEPENDPATH += .
#INCLUDEPATH += .

QT += core sql widgets

# Input
SOURCES += main.cpp \
    mainui.cpp \
    counter.cpp

HEADERS += \
    mainui.h \
    counter.h

FORMS += \
    mainui.ui
